class AppStrings {
  static const appTitle = 'Stock Market App';
  static const searchAndAddScrips = 'Search and Add Scrips';
  static const searchHint = 'Search';
  static const create = 'Create';
  static const createNewWatchlist = 'Create New Watchlist';
  static const editCurrentWatchlist = 'Edit Current Watchlist';
  static const manageWatchlists = 'Manage Watchlists';
  static const renameWatchlist = 'Rename Watchlist';
  static const newName = 'New name';
  static const cancel = 'Cancel';
  static const delete = 'Delete';
  static const rename = 'Rename';
  static const areYouSureDelete = 'Are you sure you want to delete';
  static const watchlistNameExists = 'A watchlist with this name already exists';
  static const maxWatchlists = 'You can only have atmost 5 watchlists';
  static const watchlistFull = 'Watchlist is full';
  static const noStocksInWatchlist = 'No stocks in this watchlist';
  static const tapToAddStocks = 'Tap the search bar to add stocks';
  static const editWatchlist = 'Edit Watchlist';
  static const orders = 'Orders';
  static const portfolio = 'Portfolio';
  static const movers = 'Movers';
  static const products = 'Products';
  static const ok = 'Ok';
  static const watchlistName = 'Watchlist Name';
  static const watchlistNameEmptyAlert =  'Watchlist name cannot be empty';
  static const watchlistFullAlert ='Your current watchlist is full 20/20. Please delete some stocks in order to add new stocks or else create a new watchlist.';
}